ADZUNA_APP_ID = "f14082e2"
ADZUNA_APP_KEY = "a90e4e74c96464e54be17538c77eea93"
**Ctrl + S**

---

## Step 2 — Open .gitignore

Click `.gitignore` in the left sidebar. Paste this into that file:
```
.streamlit/secrets.toml
__pycache__/
*.pyc